version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - internal_network
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - internal_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "youruser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  db-data:
